export const catsData = [
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "https://media.giphy.com/media/W0VuY0dTxH9L6vLUJ2/giphy.gif",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody", "insomniac"],
        isGif: false,
        image: "https://media.giphy.com/media/WNcb7X5QHgr9cqWm1S/giphy.gif",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "https://media.giphy.com/media/eLv7gJpxqiQtbNNQUe/giphy.gif",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant", "moody"],
        isGif: false,
        image: "https://media.giphy.com/media/yFQ0ywscgobJK/giphy.gif",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: false,
        image: "https://media.giphy.com/media/mlvseq9yvZhba/giphy.gif",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "https://media.giphy.com/media/8vQSQ3cNXuDGo/giphy.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "https://media.giphy.com/media/mlvseq9yvZhba/giphy.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "https://media.giphy.com/media/l0ExdMHUDKteztyfe/giphy.gif",
        alt: "A cat looking insomniac",
    },{

        emotionTags: ["moody"],
        isGif: true,
        image: "https://media.giphy.com/media/YmVNzDnboB0RQEpmLr/giphy.gif",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "https://media.giphy.com/media/vySkPlXaNO0ElMIkeo/giphy.gif",
        alt: "A cat looking angry",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "https://media.giphy.com/media/blPpTGDhn6hEI/giphy.gif",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "https://media.giphy.com/media/BMR4cgypuglVu/giphy.gif",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "https://media.giphy.com/media/ToCRja2miF3Xi/giphy.gif",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry", "sad", "confused"],
        isGif: true,
        image: "https://media.giphy.com/media/ODy29v7YAJrck/giphy.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://media.giphy.com/media/4AZM3gcrWqoKndGYiy/giphy.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://media.giphy.com/media/g4U5xxwZlz8ME/giphy.gif",
        alt: "A cat looking hungry",
    }, {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://media.giphy.com/media/Uoc6tZqI8AWGc/giphy.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac", "scared"],
        isGif: true,
        image: "https://media.giphy.com/media/mlvseq9yvZhba/giphy.gif",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "https://media.giphy.com/media/dIVa0pwco4Mj5rQ7gy/giphy.gif",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "https://media.giphy.com/media/aC45M5Q4D07Pq/giphy.gif",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "https://media.giphy.com/media/q1MeAPDDMb43K/giphy.gif",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "https://media.giphy.com/media/6byDVsPwzrz9K/giphy.gif",
        alt: "A cat looking scared",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "https://media.giphy.com/media/1DTBGm5Rfgymk/giphy.gif",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["nerd", "moody"],
        isGif: true,
        image: "https://media.giphy.com/media/xT77XZrTKOxycjaYvK/giphy.gif",
        alt: "A cat looking nerd",
    },
      {emotionTags: ["dance"],
        isGif: true,
        image: "https://media.giphy.com/media/WXB88TeARFVvi/giphy.gif",
        alt: "A cat dancing",
    },
    {emotionTags: ["dance"],
        isGif: true,
        image: "https://media.giphy.com/media/BK1EfIsdkKZMY/giphy.gif",
        alt: "A cat dancing",
    },
    {emotionTags: ["insomniac"],
        isGif: false,
        image: "pumpkin.png",
        alt: "A cat wirdy",
    },
]
